version: "3"
services:
  postgresql:
    container_name: fiesta-database
    image: postgres:17.0
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - psql-data:/var/lib/postgresql/data

volumes:
  psql-data:
